site_name: numqi
site_url: https://husisy.github.io/numqi/
theme:
  name: material
  features:
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial:
    - tutorial/get_started.ipynb
    - tutorial/gellmann.ipynb
    - tutorial/dicke_basis.ipynb
    - tutorial/random.ipynb
    - optimize:
      - tutorial/optimize/basic.ipynb
      - tutorial/optimize/wiki-test-function.ipynb
      - tutorial/optimize/adam-vs-lbfgs.ipynb
      - tutorial/optimize/wiki-test-function-ALM.ipynb
    - tutorial/parametrize.ipynb
    - matrix space:
      - tutorial/matrix_space/numerical_range.ipynb
      - tutorial/matrix_space/numerical_range1.ipynb
      - tutorial/matrix_space/space_schmidt_rank.ipynb
      - tutorial/matrix_space/space_schmidt_rank_real.ipynb
    - group:
      - basic: tutorial/group/basic.md
      - Clifford: tutorial/group//spf2.md
      - symmetric extension: tutorial/group/symext.md
    - quantum error correction:
      - tutorial/qecc/basic.md
      - tutorial/qecc/varqecc.ipynb
      - tutorial/qecc/qecc733.ipynb
    - simulator:
      - tutorial/simulator/basic.ipynb
      - tutorial/simulator/customized_gate.ipynb
    - entanglement:
      - tutorial/entangle/dm_numerical_range.ipynb
      - tutorial/entangle/special_state.md
      - tutorial/entangle/dm_cross_section.ipynb
      - tutorial/entangle/basic.ipynb
      - tutorial/entangle/advanced00.ipynb
      - "Entanglement: Advanced 1": tutorial/entangle/advanced01.md
      - "Entanglement: Advanced 2": tutorial/entangle/advanced02.md
      - tutorial/entangle/cha.ipynb
      - tutorial/entangle/various_JANR.ipynb
      - pure bosonic extension: tutorial/entangle/pureb.md
      - symmetric extension: tutorial/entangle/symext.md
    - optimal-control:
      - dynamic simulation: tutorial/optimal_control/simulate_dynamics.ipynb
    - tutorial/maxent.ipynb
    - tutorial/query_grover.ipynb
  - API:
    - matrix space: api/matrix_space.md
    - random: api/random.md
    - dicke: api/dicke.md
    - parameterization: api/param.md
    - quantum gate: api/gate.md
    - entanglement detection: api/entangle.md
  - misc: misc.md
plugins:
  search:
  mkdocs-jupyter:
    include: ["*.ipynb"] # Default: ["*.py", "*.ipynb"]
    execute: true
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [python]
        options:
          docstring_style: google
          show_source: false
          show_root_heading: true
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# TODO add colab link
