site_name: numqi
site_url: https://husisy.github.io/numqi/
theme:
  name: material
  features:
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: index.md
  - Installation: installation.md
  - Preliminary:
    - Clifford: preliminary/group_spf2.md
    - Dicke Basic: preliminary/dicke_basis.md
    - Entanglement Basic: preliminary/entanglement_basic.md
    - Entanglement Advanced: preliminary/entanglement_advanced.md
  - Tutorial:
    - tutorial/gellmann.ipynb
    - optimize:
      - tutorial/optimize/basic.ipynb
      - tutorial/optimize/wiki-test-function.ipynb
      - tutorial/optimize/adam-vs-lbfgs.ipynb
      - tutorial/optimize/wiki-test-function-ALM.ipynb
    - tutorial/parametrize.ipynb
    - matrix space:
      - tutorial/matrix_space/numerical_range.ipynb
    - group:
      - group: tutorial/group.md
      - symmetric extension: tutorial/group-symext.md
    - maximum entropy: tutorial/maxent.md
    - quantum error correction: tutorial/qecc.md
    - entanglement:
      - tutorial/entangle/dm_numerical_range.ipynb
      - tutorial/entangle/dm_cross_section.ipynb
      - tutorial/entangle/entanglement_basic.ipynb
      - tutorial/entangle/entanglement_advanced.ipynb
      - tutorial/entangle/cha.ipynb
      - tutorial/entangle/various_JANR.ipynb
      - pure bosonic extension: tutorial/entangle/pureb.md
      - symmetric extension: tutorial/entangle/symext.md
    - optimal-control:
      - dynamic simulation: tutorial/optimal_control/simulate_dynamics.ipynb
  - API:
    - matrix space: api/matrix_space.md
    - random: api/random.md
    - parameterization: api/param.md
    - quantum gate: api/gate.md
    - quantum circuit: api/circuit.md
    - entanglement detection: api/entangle.md
  - misc: misc.md
plugins:
  search:
  mkdocs-jupyter:
    include: ["*.ipynb"] # Default: ["*.py", "*.ipynb"]
    execute: true
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [python]
        options:
          docstring_style: google
          show_source: false
          show_root_heading: true
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# TODO add colab link
