site_name: numqi
# site_url: https://husisy.github.io/demo-mkdocs/
theme:
  name: material
  features:
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: index.md
  - Preliminary:
    - Symplectic: preliminary/group_spf2.md
  - Tutorial:
    - optimize: tutorial/optimize.md
    - gradient: tutorial/gradient_descent.md
    - group:
      - group: tutorial/group.md
      - symmetric extension: tutorial/group-symext.md
  - API:
    - matrix space: api/matrix_space.md
    - random: api/random.md
    - parameterization: api/param.md
    - quantum gate: api/gate.md
    - quantum circuit: api/circuit.md
  - misc: misc.md
plugins:
  search:
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [python]
        options:
          docstring_style: google
          show_source: false
          show_root_heading: true
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# mkdocs serve --dev-addr=127.0.0.1:23333
